add date modified and size
yashdavisgupta/Asperitas pull request #6
Opened 2021-02-13 05:13 UTC by yashdavisgupta

resolves #1

2021-02-18 01:46 UTC, AlexanderOtavka requested changes
I can't finish the review until you fix the error, but the code seems fine

2021-02-18 01:46 UTC, AlexanderOtavka commented on cli.js
> -asp.setcwd(dir, argv.include, argv.exclude);
This looks like a mistake.  I think it's causing this error on startup:
```
web_1  | TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
web_1  |     at Object.readdir (fs.js:996:10)
web_1  |     at readRoots (/usr/app/lib/index.js:59:8)
web_1  |     at exports.get (/usr/app/lib/index.js:86:5)
web_1  |     at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)
web_1  |     at next (/usr/app/node_modules/express/lib/router/route.js:137:13)
web_1  |     at Route.dispatch (/usr/app/node_modules/express/lib/router/route.js:112:3)
web_1  |     at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)
web_1  |     at /usr/app/node_modules/express/lib/router/index.js:281:22
web_1  |     at Function.process_params (/usr/app/node_modules/express/lib/router/index.js:335:12)
web_1  |     at next (/usr/app/node_modules/express/lib/router/index.js:275:10)
```

2021-02-18 02:06 UTC, yashdavisgupta commented
Should work now

2021-02-20 20:59 UTC, YourFin approved these changes
Looks OK to me

2021-02-20 20:59 UTC, YourFin commented on app/app.js
> +      tr.setAttribute("onclick","refreshTable('"+path+"'); currentPath = '"+data[file].Path+"';");
I do not envy writing code like this

2021-02-20 21:00 UTC, YourFin approved these changes
Looks OK to me

2021-02-21 02:42 UTC, merged